Enabled commands configuration:
  #Activation (true) ou non (false) du  flag RP pour les regions world guard (necessite world guard et world guard custom flags)
  Use WG RP region flag: true
  #Activation (true) ou non (false) des différentes fonctions du plug in
  Permissions: true
  RP: true
  RPReload: true
  Think: true
  Shout: true
  Destin: true
  Loot: true
  Do: true
  Spy: true
  Voice Range: true
RP chat colors configuration:

  #ForbiddenColors permet de définir les couleurs qui ne sont pas choisissable pour le /rp.
  Forbidden Colors:
  - BLACK
  - DARK_BLUE
  - DARK_AQUA
  - DARK_RED
  - DARK_PURPLE
  - GOLD
  - GRAY
  - DARK_GRAY
  - BLUE
  - GREEN
  - AQUA
  - RED
  - YELLOW
  - WHITE
  - MAGIC
  - BOLD
  - STRIKETHROUGH
  - UNDERLINE
  - ITALIC
  - RESET
  
  #Authorised Colors est purement informative, elle permet seulement de voir quelles
  #couleurs sont encore autorisées dans la liste complete.
  Authorised Colors:
  - DARK_GREEN
  - LIGHT_PURPLE
  
  #Default RP Color permet de choisir la couleur dans laquelle apparaitront les dires
  # des personnes ayant tout juste activé le mode RP sans en changer la couleur.
  #
  Default RP color: DARK_GREEN
Voice range configuration:
  #Distance en blocs de la portée de voix normale
  Voice range: 40
  
  #Activation(true) ou non(false) de la portée de voix pour chaque commande
  RP voice range enabled: true
  Think voice range enabled: true
  Shout voice range enabled: true
  Destin voice range enabled: true
  Loot voice range enabled: true
  Do voice range enabled: true
Destiny roll dice configuration:
  #La chance de gagner son action lors d'un /destin
  Win chance percentage (100 and more to always win): 25
